### ISSUE TITLE
Question: Removed javascript region support

### ISSUE THREAD

**Issue by KkFalse2** [madskristensen/WebEssentials2017#10] opened 2017-03-24 09:30 UTC
### Installed product versions
- Visual Studio Professional 2017 : VisualStudio/15.0.0+26228.9 (up-to-date)
- Web Essentials 2017 v1.5.8 (up-to-date)

### Description
Javascript //#region support seems to have been removed from WebEssentials 2017 (works great in WebEssentials 2015.3)
FYI, an equivalent question was asked on the marketplace by Joe Green on 3/9/2017 in the User Reviews section.
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebExtensionPack2017

### Steps to recreate
1. Create a new JS file in a web project
2. Surround a code block with 
`//#region Private functions`
`....<<code block>>....`
`//#endregion Private functions`

### Current behavior
The region is not recognised by the VS2017 IDE, you cant fold/unfold it unlike in VS2015.3 with WebEssentials 2015.3.

### Expected behavior
The region can be fold/unfold.

Or if it's no longer part of WebEssentials, is there another extension to do so on the marketplace?

*Thank you for your answers.*

**Comment by madskristensen** [comment] 2017-03-28 15:52
Dupe of #7 

Get this extension: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.JavaScriptRegions

**Closed by madskristensen** 2017-03-28 15:52 UTC
